In [1]:
import numpy as np
import pandas as pd

# 20. Series - Part One

In [2]:
myindex = ['USA', 'Canada', 'Mexico']

In [3]:
mydata = [1776, 1867, 1821]

In [4]:
myser = pd.Series(data=mydata, index=myindex)

In [5]:
myser

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [6]:
myser.iloc[0]

1776

In [7]:
myser.loc['USA']

1776

In [8]:
ages = {'Sam':5, 'Frank':10, 'Spike':7}

In [9]:
pd.Series(ages)

Sam       5
Frank    10
Spike     7
dtype: int64

# Coding Exercise 4: Check-in: Labeled Index in Pandas Series

In [10]:
# TASK: Use pandas to grab the expenses paid by Bob.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
#  Link to Solution: https://gist.github.com/Pierian-Data/3d7f7cb3528f015d9584d04a7168b97f
expenses = pd.Series({'Andrew':200,'Bob':150,'Claire':450})

bob_expense = expenses.loc['Bob']
bob_expense

150

# 21. Series - Part Two

In [11]:
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100, 'China': 500, 'India': 210, 'USA': 260}

In [12]:
sales_q1 = pd.Series(q1)

In [13]:
sales_q2 = pd.Series(q2)

In [14]:
sales_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [15]:
sales_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [16]:
sales_q1['Japan']
sales_q1.iloc[0]

80

In [17]:
sales_q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [18]:
sales_q1.values

array([ 80, 450, 200, 250], dtype=int64)

In [19]:
# [1, 2] * 2
np.array([1, 2]) * 2

array([2, 4])

In [20]:
# sales_q1 * 2
sales_q1 / 100

Japan    0.8
China    4.5
India    2.0
USA      2.5
dtype: float64

In [21]:
sales_q1 + sales_q2 # NaN is added for the missing values in the series

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [22]:
first_half = sales_q1.add(sales_q2, fill_value=0) # fill_value=0 is used to fill the missing values with 0

In [23]:
sales_q1.dtypes

dtype('int64')

In [24]:
first_half.dtypes

dtype('float64')

# 22. DataFrames - Part One - Creating a DataFrame

In [29]:
np.random.seed(101) # to get the same random numbers
mydata = np.random.randint(0, 101, (4, 3))
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [30]:
myindex = ['CA', 'NY', 'AZ', 'TX']

In [31]:
mycolumns = ['Jan', 'Feb', 'Mar']

In [33]:
df = pd.DataFrame(data=mydata, index=myindex, columns=mycolumns)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 252.0+ bytes


In [46]:
df = pd.read_csv(r'data_frame\tips.csv')
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

# 23. DataFrames - Part Two - Basic Properties