In [2]:
from unittest import skipIf

with open(r'F:\DataSpell\data_science_ml_learning\DATA\One.txt') as mytext:
    print(mytext.read())

This is a story about dogs
our canine pets
Dogs are furry animals



In [3]:
with open(r'F:\DataSpell\data_science_ml_learning\DATA\Two.txt') as mytext:
    print(mytext.read())

This story is about surfing
Catching waves is fun
Surfing is a popular water sport



In [4]:
with open(r'F:\DataSpell\data_science_ml_learning\DATA\One.txt') as mytext:
    entire_text = mytext.read()

In [5]:
entire_text

'This is a story about dogs\nour canine pets\nDogs are furry animals\n'

In [6]:
print(entire_text)

This is a story about dogs
our canine pets
Dogs are furry animals



In [7]:
with open(r'F:\DataSpell\data_science_ml_learning\DATA\One.txt') as mytext:
    lines = mytext.readlines()

In [8]:
lines

['This is a story about dogs\n',
 'our canine pets\n',
 'Dogs are furry animals\n']

In [9]:
with open(r'F:\DataSpell\data_science_ml_learning\DATA\One.txt') as f:
    words = f.read().lower().split()

In [10]:
words

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [11]:
with open(r'F:\DataSpell\data_science_ml_learning\DATA\One.txt') as f:
    words_one = f.read().lower().split()

In [12]:
words_one

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [13]:
len(words_one)

13

In [14]:
uni_words_one = set(words)

In [15]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [16]:
with open(r'F:\DataSpell\data_science_ml_learning\DATA\Two.txt') as f:
    words_two = f.read().lower().split()
    uni_words_two = set(words_two)

In [17]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [18]:
all_uni_words = set()
all_uni_words.update(uni_words_one)
all_uni_words.update(uni_words_two)

In [19]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [20]:
full_vocab = dict()
i = 0

for word in all_uni_words:
    full_vocab[word] = i
    i = i+1

In [21]:
full_vocab

{'is': 0,
 'story': 1,
 'catching': 2,
 'surfing': 3,
 'fun': 4,
 'dogs': 5,
 'canine': 6,
 'pets': 7,
 'popular': 8,
 'are': 9,
 'our': 10,
 'water': 11,
 'furry': 12,
 'waves': 13,
 'a': 14,
 'this': 15,
 'about': 16,
 'sport': 17,
 'animals': 18}

In [22]:
one_freq = [0]*len(full_vocab)
two_freq = [0]*len(full_vocab)
all_words = ['']*len(full_vocab)

In [23]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [24]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [25]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [26]:
for word in full_vocab:
    word_ind = full_vocab[word]
    all_words[word_ind] = word

In [27]:
all_words

['is',
 'story',
 'catching',
 'surfing',
 'fun',
 'dogs',
 'canine',
 'pets',
 'popular',
 'are',
 'our',
 'water',
 'furry',
 'waves',
 'a',
 'this',
 'about',
 'sport',
 'animals']

In [29]:
with open(r'F:\DataSpell\data_science_ml_learning\DATA\One.txt') as f:
    one_text = f.read().lower().split()

for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind]+=1

In [30]:
one_freq

[1, 1, 0, 0, 0, 2, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1]

In [31]:
with open(r'F:\DataSpell\data_science_ml_learning\DATA\Two.txt') as f:
    two_text = f.read().lower().split()

for word in two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind]+=1

In [32]:
two_freq

[3, 1, 1, 2, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0]

In [34]:
import pandas as pd

In [35]:
pd.DataFrame(data=[one_freq,two_freq],columns=all_words)

is  story  catching  surfing  fun  dogs  canine  pets  popular  are  our  \
0   1      1         0        0    0     2       1     1        0    1    1   
1   3      1         1        2    1     0       0     0        1    0    0   

   water  furry  waves  a  this  about  sport  animals  
0      0      1      0  1     1      1      0        1  
1      1      0      1  1     1      1      1        0

In [36]:
text = ['This is a line',
        "This is another line",
        "Completely different line"]

In [37]:
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer, CountVectorizer

In [38]:
cv = CountVectorizer()

In [39]:
cv.fit_transform(text)

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [40]:
sparse_mat = cv.fit_transform(text)

In [41]:
sparse_mat.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [42]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [43]:
cv = CountVectorizer(stop_words='english')

In [45]:
cv.fit_transform(text).todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [46]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [47]:
tfidf_transformer = TfidfTransformer()

In [48]:
cv = CountVectorizer()

In [49]:
counts = cv.fit_transform(text)

In [51]:
counts

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [52]:
tfidf = tfidf_transformer.fit_transform(counts)

In [53]:
tfidf.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [55]:
from sklearn.pipeline import Pipeline

In [56]:
pipe = Pipeline([('cv',CountVectorizer()),('tfidf',TfidfTransformer())])

In [57]:
results = pipe.fit_transform(text)

In [58]:
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [59]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [60]:
tfidf = TfidfVectorizer()

In [61]:
new = tfidf.fit_transform(text)

In [62]:
new.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])