In [1]:
from unittest import skipIf

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../../DATA/Advertising.csv')

In [3]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [4]:
X = df.drop('sales', axis=1)

In [5]:
y = df['sales']

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [8]:
poly_features = polynomial_converter.fit_transform(X)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=.3, random_state=101)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

In [13]:
scaler.fit(X_train)

StandardScaler()

In [14]:
X_train = scaler.fit_transform(X_train)

In [15]:
X_test = scaler.transform(X_test)

In [16]:
from sklearn.linear_model import Ridge

In [17]:
ridge_model = Ridge(alpha=10)

In [18]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [19]:
test_predictions = ridge_model.predict(X_test)

In [20]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [21]:
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)
MAE = mean_absolute_error(y_test, test_predictions)

In [22]:
print(f'MAE: {MAE} \nMSE: {MSE} \nRMSE: {RMSE}')

MAE: 0.5774404204714173 
MSE: 0.8003783071528403 
RMSE: 0.8946386461319678


In [23]:
from sklearn.linear_model import RidgeCV

In [34]:
ridge_model = RidgeCV(alphas=(0.001, 0.01, 0.1, 0.5, 1.0, 5, 7, 10) ,scoring='neg_mean_absolute_error')

In [35]:
ridge_model.fit(X_train, y_train)

RidgeCV(alphas=(0.001, 0.01, 0.1, 0.5, 1.0, 5, 7, 10),
        scoring='neg_mean_absolute_error')

In [36]:
test_predictions = ridge_model.predict(X_test)

In [37]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [38]:
MAE = mean_absolute_error(y_test, test_predictions)

In [39]:
MSE = mean_squared_error(y_test, test_predictions)

In [40]:
RMSE = np.sqrt(MSE)

In [41]:
print(f'MAE {MAE}, \nMSE {MSE} \nRMSE {RMSE}')

MAE 0.41018731836621086, 
MSE 0.3398436278231483 
RMSE 0.5829610860281742


In [42]:
ridge_model.alpha_

0.01

In [43]:
from sklearn.linear_model import LassoCV

In [44]:
lasso_cv_model = LassoCV(eps=0.1, n_jobs=-1, n_alphas=100, cv=5)

In [45]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1, n_jobs=-1)

In [46]:
lasso_cv_model.alpha_

0.49430709092258285

In [47]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [48]:
print(f'MAE {MAE}, \nMSE {MSE} \nRMSE {RMSE}')

MAE 0.41018731836621086, 
MSE 0.3398436278231483 
RMSE 0.5829610860281742


In [49]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [50]:
from sklearn.linear_model import ElasticNetCV

In [51]:
elastic_model = ElasticNetCV(n_jobs=-1, l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], tol=0.01)

In [52]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], n_jobs=-1, tol=0.01)

In [53]:
test_predictions = elastic_model.predict(X_test)

In [54]:
test_predictions

array([13.45305348, 19.18063235, 12.24742524, 16.38929906,  8.23763296,
        7.30560324, 19.99551548, 17.39684667, 10.53450151, 20.11322169,
        9.49258534, 14.00256551, 12.24336724, 23.4621135 , 19.63662668,
        9.39212755, 12.3271164 ,  9.11395345,  8.4895916 , 21.71116798,
        7.47516402, 19.30242856, 27.75926837, 24.8294422 ,  8.95023677,
       11.98452278, 20.12067434,  9.22569092, 12.6872445 ,  8.56714992,
        8.99446834, 20.19604421, 10.85400268,  7.30892788, 18.22303733,
        9.33711524, 10.26890258,  9.51513049,  7.85147594, 11.04856164,
       12.4385734 , 10.6316101 , 11.15283476,  7.94836919, 11.42868187,
       10.33293983,  6.76878189, 15.45176389, 13.34443448, 22.76661906,
       10.44657641, 13.24914629, 14.13377553, 11.76768891, 11.85732983,
        6.00849416, 25.27446859,  9.54290254, 17.15133504, 15.66124021])

In [55]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

In [56]:
print(f'MAE {MAE}, \nMSE {MSE} \nRMSE {RMSE}')

MAE 0.566326211756945, 
MSE 0.5603340214638837 
RMSE 0.7485546215633724


In [58]:
elastic_model.l1_ratio_

1.0

In [59]:
elastic_model.alpha_

0.004943070909225828

In [60]:
elastic_model.coef_

array([ 3.78993643,  0.89232919,  0.28765395, -1.01843566,  2.15516144,
       -0.3567547 , -0.271502  ,  0.09741081,  0.        , -1.05563151,
        0.2362506 ,  0.07980911,  1.26170778,  0.01464706,  0.00462336,
       -0.39986069,  0.        ,  0.        , -0.05343757])