In [1]:
import numpy as np
import pandas as pd

In [2]:
my_list = [1, 2, 3]

In [3]:
my_array = np.array(my_list)

In [4]:
my_array

array([1, 2, 3])

In [5]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_array

array([1, 2, 3])

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
pd.DataFrame(np.arange(0, 50))

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19
20  20
21  21
22  22
23  23
24  24
25  25
26  26
27  27
28  28
29  29
30  30
31  31
32  32
33  33
34  34
35  35
36  36
37  37
38  38
39  39
40  40
41  41
42  42
43  43
44  44
45  45
46  46
47  47
48  48
49  49

In [8]:
np.arange(0, 50, 10)

array([ 0, 10, 20, 30, 40])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((9, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [13]:
pd.DataFrame(np.linspace(0, 10, 85))

0
0    0.000000
1    0.119048
2    0.238095
3    0.357143
4    0.476190
..        ...
80   9.523810
81   9.642857
82   9.761905
83   9.880952
84  10.000000

[85 rows x 1 columns]

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.43201546, 0.80004048, 0.57058058, 0.31986886, 0.57431372])

In [16]:
np.random.rand(5, 5)

array([[0.60513579, 0.03115908, 0.60576424, 0.35089163, 0.12806909],
       [0.08031966, 0.72987722, 0.98721432, 0.09607079, 0.45336395],
       [0.42055264, 0.82697432, 0.72228453, 0.23373057, 0.13676803],
       [0.4776796 , 0.15437724, 0.97741455, 0.32134475, 0.78289249],
       [0.51022814, 0.60076319, 0.49704681, 0.15206097, 0.20134186]])

In [17]:
np.random.randn(2)

array([-1.55761702, -0.36586799])

In [18]:
np.random.rand(1, 100).transpose()
np.random.randint(1, 100)

17

In [19]:
np.random.randint(1, 100, 24).reshape(6, 4)

array([[50, 35, 83, 50],
       [96, 80, 63, 53],
       [73, 96, 89, 48],
       [24, 13,  2, 58],
       [38, 60, 12, 53],
       [82, 55, 76, 12]])

In [20]:
np.random.seed(42)
np.random.rand(8)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615])

In [21]:
np.random.seed(42)
np.random.randint(1, 100, 24).reshape(6, 4)

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24],
       [ 3, 22, 53,  2],
       [88, 30, 38,  2],
       [64, 60, 21, 33]])

In [22]:
np.random.randint(1, 10, 24)

array([6, 9, 1, 3, 7, 4, 9, 3, 5, 3, 7, 5, 9, 7, 2, 4, 9, 2, 9, 5, 2, 4,
       7, 8])

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([46, 34, 13, 16, 35, 49, 39,  3,  1,  5])

In [26]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.reshape(2, 5)

array([[46, 34, 13, 16, 35],
       [49, 39,  3,  1,  5]])

In [28]:
ranarr.max()

49

In [29]:
arr.min()

0

In [30]:
arr.shape

(25,)

In [31]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [32]:
arr.dtype

dtype('int32')

# 01-NumPy-Indexing-and-Selection

In [33]:
arr = np.arange(0, 11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[8]

8

In [39]:
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [42]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[0:5] = 100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr = np.arange(0, 11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
slice_of_arr = arr[0:6]

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[:] = 99

In [55]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_copy = arr.copy()

In [59]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr_2d = np.array(([5, 10, 20], [9, 8, 7], [66, 55, 44]))

In [63]:
arr_2d[1]

array([9, 8, 7])

In [64]:
arr_2d[1][0]

9

In [66]:
arr_2d

array([[ 5, 10, 20],
       [ 9,  8,  7],
       [66, 55, 44]])

In [67]:
arr_2d[:2,1:]

array([[10, 20],
       [ 8,  7]])

In [68]:
arr_2d[2]

array([66, 55, 44])

In [71]:
arr_2d[2, :2]

array([66, 55])

In [72]:
arr_2d[0, 3:5]

array([], dtype=int32)

In [73]:
arr = np.arange(1, 11)

In [75]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
all(arr > 4)

False

In [79]:
bool_arr = arr > 4

In [81]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [83]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [84]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
x = 2

arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# 02-NumPy-Operations

In [89]:
arr = np.arange(0, 11)

In [90]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [91]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [92]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [94]:
arr / arr

C:\Users\Zygim\AppData\Local\Temp\ipykernel_37428\2811617162.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [97]:
1 / arr

C:\Users\Zygim\AppData\Local\Temp\ipykernel_37428\2495778407.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [99]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [100]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [101]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [102]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [104]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [105]:
np.log(arr)

C:\Users\Zygim\AppData\Local\Temp\ipykernel_37428\2931416741.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [106]:
arr = np.arange(0, 15)

In [108]:
arr.sum()

105

In [109]:
arr.mean()

7.0

In [110]:
arr.max()

14

In [112]:
arr.min()

0

In [120]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [122]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [125]:
arr_2d.sum(axis=1)

array([10, 26, 42])