In [2]:
import numpy as np
import pandas as pd

In [3]:
my_list = [1, 2, 3]

In [4]:
my_array = np.array(my_list)

In [6]:
my_array

array([1, 2, 3])

In [8]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_array

array([1, 2, 3])

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
pd.DataFrame(np.arange(0, 50))

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19
20  20
21  21
22  22
23  23
24  24
25  25
26  26
27  27
28  28
29  29
30  30
31  31
32  32
33  33
34  34
35  35
36  36
37  37
38  38
39  39
40  40
41  41
42  42
43  43
44  44
45  45
46  46
47  47
48  48
49  49

In [24]:
np.arange(0, 50, 10)

array([ 0, 10, 20, 30, 40])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((9, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [43]:
pd.DataFrame(np.linspace(0, 10, 85))

0
0    0.000000
1    0.119048
2    0.238095
3    0.357143
4    0.476190
..        ...
80   9.523810
81   9.642857
82   9.761905
83   9.880952
84  10.000000

[85 rows x 1 columns]

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.random.rand(5)

array([0.97351624, 0.46143737, 0.71028309, 0.07587797, 0.41117167])

In [47]:
np.random.rand(5, 5)

array([[0.72914358, 0.00677067, 0.39092766, 0.46903882, 0.29983549],
       [0.42462219, 0.76650169, 0.34492668, 0.07396924, 0.6340145 ],
       [0.35142245, 0.70198266, 0.12489416, 0.88988963, 0.01862017],
       [0.04665482, 0.8905212 , 0.13316504, 0.12580466, 0.48086525],
       [0.68770515, 0.6340747 , 0.79819977, 0.44257374, 0.08110662]])

In [55]:
np.random.randn(2)

array([ 0.28398013, -0.10303486])

In [59]:
np.random.rand(1, 100).transpose()
np.random.randint(1, 100)

50

In [69]:
np.random.randint(1, 100, 24).reshape(6, 4)

array([[73, 31, 47, 36],
       [28, 49, 90, 50],
       [15, 84, 28, 45],
       [60, 98, 96, 86],
       [99, 34, 76, 75],
       [91, 51, 94, 24]])

In [73]:
np.random.seed(42)
np.random.rand(8)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615])

In [79]:
np.random.seed(42)
np.random.randint(1, 100, 24).reshape(6, 4)

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24],
       [ 3, 22, 53,  2],
       [88, 30, 38,  2],
       [64, 60, 21, 33]])

In [104]:
np.random.randint(1, 10, 24)

array([3, 7, 6, 8, 9, 5, 1, 3, 8, 6, 8, 9, 4, 1, 1, 4, 7, 2, 3, 1, 5, 1,
       8, 1])

In [105]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [107]:
ranarr

array([48,  1,  1, 27, 22, 36, 31, 32,  0, 18])

In [108]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [109]:
ranarr.reshape(2, 5)

array([[48,  1,  1, 27, 22],
       [36, 31, 32,  0, 18]])

In [111]:
ranarr.max()

48

In [112]:
arr.min()

0

In [114]:
arr.shape

(25,)

In [118]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [119]:
arr.dtype

dtype('int32')

# 01-NumPy-Indexing-and-Selection