In [1]:
import pandas as pd
import numpy as np

# 14. NumPy Arrays

In [2]:
my_list = [1, 2, 3]

In [3]:
my_array = np.array([1, 2, 3])

In [4]:
my_array

array([1, 2, 3])

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix) # makes a 2D array from a list of lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10) # creates numpy range array 
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [10]:
np.zeros(5) # creates an array of zeros 0. indicates float

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2, 5)) # creates a 2D array of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((4, 4)) # creates a 2D array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0, 10, 3) # creates an array of 3 evenly spaced numbers between 0 and 10
np.linspace(0, 10, 11) # 11 numbers between 0 and 10
np.linspace(0, 10, 21) 

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [14]:
np.eye(5) # creates an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5) # creates an array of 5 random numbers between 0 and 1      
np.random.rand(5, 6) # creates a 2D array of random numbers

array([[0.51515992, 0.65825424, 0.24721706, 0.34641582, 0.09973579,
        0.7755697 ],
       [0.84700626, 0.28912661, 0.28127927, 0.74849192, 0.99538413,
        0.28039876],
       [0.1565749 , 0.65733606, 0.98797676, 0.8623383 , 0.31691308,
        0.34559724],
       [0.74210924, 0.91487508, 0.21086469, 0.5122022 , 0.41232551,
        0.37689621],
       [0.19513296, 0.55111597, 0.10538844, 0.93171947, 0.84327873,
        0.36059022]])

In [16]:
np.random.randn(10) # creates an array of 10 random numbers from a standard normal distribution

array([ 0.78923393,  0.4557649 ,  0.07753182,  1.0751347 , -0.15076593,
       -0.11284129, -0.48414487, -1.53153456, -0.5867859 , -0.61456626])

In [17]:
np.random.randint(0, 101, 5) # creates an array of 5 random integers between 0 and 100
np.random.randint(0, 101, (4, 5)) # creates an array of 5 random integers between 0 and 100

array([[26, 17, 87, 78, 94],
       [98,  9,  3, 42,  2],
       [14, 89, 94, 89, 53],
       [91, 14, 49, 25, 56]])

In [18]:
np.random.seed(42) # sets the seed for reproducibility 
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [19]:
arr = np.arange(0, 25)

In [20]:
arr.reshape(5, 5) # reshapes the array into a 5x5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
ranarr = np.random.randint(0, 101, 10)

In [22]:
ranarr.max() # returns the maximum value in the array

99

In [23]:
ranarr.min() # returns the minimum value in the array

2

In [24]:
ranarr.argmax() # returns the index of the maximum value in the array

5

In [25]:
ranarr.argmin() # returns the index of the minimum value in the array

7

In [26]:
ranarr.dtype # returns the data type of the array

dtype('int32')

In [27]:
ranarr.shape # returns the shape of the array

(10,)

In [28]:
arr = arr.reshape(5, 5)

In [29]:
arr.shape

(5, 5)

In [30]:
arr.reshape(25, 1) # reshapes the array into a 25x1 matrix
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

# 15. NumPy Indexing and Selection

In [31]:
arr = np.arange(0, 11)

In [35]:
arr[8]

8

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[:5]

array([0, 1, 2, 3, 4])

In [41]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[0:5] = 100

In [45]:
arr 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [46]:
arr = np.arange(0, 11)

In [48]:
slice_of_arr = arr[0:5]

In [50]:
slice_of_arr[:] = 99

In [52]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [57]:
arr_copy = arr.copy()

In [59]:
arr_copy[:] = 100

In [61]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [67]:
arr_2d.shape

(3, 3)

In [69]:
arr_2d[0]

array([ 5, 10, 15])

In [71]:
arr_2d[-1]

array([35, 40, 45])

In [75]:
arr_2d[1][1]
arr_2d[1, 1]
arr_2d[0,2]

15

In [78]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [81]:
arr_2d[:2, :1]

array([[ 5],
       [20]])

In [82]:
arr = np.arange(1, 11)

In [83]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
bool_arr = arr > 4

In [91]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [92]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

# Coding Exercise 2: Coding Exercise Check-in: Selecting Data from Numpy Array

In [93]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [96]:
bool_array = dice_rolls > 2

In [98]:
total_rolls_over_two = bool_array.sum()

In [100]:
total_rolls_over_two

19

# 16. NumPy Operations

In [101]:
arr = np.arange(0, 10)

In [104]:
arr + 5 # adds 5 to each element in the array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [105]:
arr - 2 # subtracts 2 from each element in the array

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [107]:
arr + arr # adds two arrays element-wise

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [108]:
arr - arr # subtracts two arrays element-wise

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [110]:
arr / arr # divide by zero warning but not an error

C:\Users\Zygim\AppData\Local\Temp\ipykernel_33908\644199619.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr # divide by zero warning but not an error


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [112]:
1 / arr # divide by zero warning but not an error

C:\Users\Zygim\AppData\Local\Temp\ipykernel_33908\2634129279.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr # divide by zero warning but not an error


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [114]:
np.sqrt(arr) # takes the square root of each element in the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [116]:
np.sin(arr) # takes the sine of each element in the array

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [118]:
np.log(arr) # takes the natural log of each element in the array

C:\Users\Zygim\AppData\Local\Temp\ipykernel_33908\355538002.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # takes the natural log of each element in the array


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [119]:
arr.sum() # returns the sum of all elements in the array

45

In [120]:
arr.mean() # returns the mean of all elements in the array

4.5

In [121]:
arr.max() # returns the maximum value in the array

9

In [122]:
arr.var()

8.25

In [125]:
arr.std()

2.8722813232690143

In [128]:
arr_2d = np.arange(0, 25).reshape(5, 5)

In [131]:
arr_2d.sum()

300

In [136]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [132]:
arr_2d.sum(axis=0) # returns the sum of each column

array([50, 55, 60, 65, 70])

In [133]:
arr_2d.sum(axis=1) # returns the sum of each row

array([ 10,  35,  60,  85, 110])

In [144]:
arr_2d[:, 0].sum()

50

# Coding Exercise 3: Check-In: Operations on NumPy Array

In [146]:
# TASK: Use numpy to check the total remaining in the account after the series of transactions.
# NOTE: Many different ways to do this! 
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/225a449484e12e0535fbbac2231b426b

account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

account_total =  account_transactions.sum()
account_total

2720

# 17. NumPy Exercises