In [1]:
import pandas as pd
import numpy as np

# 14. NumPy Arrays

In [2]:
my_list = [1, 2, 3]

In [3]:
my_array = np.array([1, 2, 3])

In [4]:
my_array

array([1, 2, 3])

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix) # makes a 2D array from a list of lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10) # creates numpy range array 
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [10]:
np.zeros(5) # creates an array of zeros 0. indicates float

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2, 5)) # creates a 2D array of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((4, 4)) # creates a 2D array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0, 10, 3) # creates an array of 3 evenly spaced numbers between 0 and 10
np.linspace(0, 10, 11) # 11 numbers between 0 and 10
np.linspace(0, 10, 21) 

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [14]:
np.eye(5) # creates an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5) # creates an array of 5 random numbers between 0 and 1      
np.random.rand(5, 6) # creates a 2D array of random numbers

array([[0.67972637, 0.26485716, 0.23832021, 0.35544383, 0.22284102,
        0.88755809],
       [0.48507662, 0.57603633, 0.16369833, 0.85051633, 0.26435851,
        0.11139639],
       [0.50392265, 0.86753614, 0.71679126, 0.49347681, 0.87332211,
        0.13615577],
       [0.41407825, 0.90217377, 0.74840066, 0.56038686, 0.37086089,
        0.87009881],
       [0.04630168, 0.25000296, 0.67667271, 0.87472811, 0.44609051,
        0.20752753]])

In [16]:
np.random.randn(10) # creates an array of 10 random numbers from a standard normal distribution

array([-0.50008367, -0.64536317, -1.29063072, -0.14832176,  0.92957927,
        0.87340436,  0.02187508,  0.44920285,  0.85609614,  0.40373922])

In [17]:
np.random.randint(0, 101, 5) # creates an array of 5 random integers between 0 and 100
np.random.randint(0, 101, (4, 5)) # creates an array of 5 random integers between 0 and 100

array([[61, 92, 19, 77, 66],
       [42, 77, 68, 37, 21],
       [17,  5, 40, 75, 90],
       [85,  2,  2, 78, 60]])

In [18]:
np.random.seed(42) # sets the seed for reproducibility 
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [19]:
arr = np.arange(0, 25)

In [20]:
arr.reshape(5, 5) # reshapes the array into a 5x5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
ranarr = np.random.randint(0, 101, 10)

In [22]:
ranarr.max() # returns the maximum value in the array

99

In [23]:
ranarr.min() # returns the minimum value in the array

2

In [24]:
ranarr.argmax() # returns the index of the maximum value in the array

5

In [25]:
ranarr.argmin() # returns the index of the minimum value in the array

7

In [26]:
ranarr.dtype # returns the data type of the array

dtype('int32')

In [27]:
ranarr.shape # returns the shape of the array

(10,)

In [28]:
arr = arr.reshape(5, 5)

In [29]:
arr.shape

(5, 5)

In [30]:
arr.reshape(25, 1) # reshapes the array into a 25x1 matrix
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

# 15. NumPy Indexing and Selection