In [1]:
import pandas as pd
import numpy as np

# 14. NumPy Arrays

In [2]:
my_list = [1, 2, 3]

In [3]:
my_array = np.array([1, 2, 3])

In [4]:
my_array

array([1, 2, 3])

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix) # makes a 2D array from a list of lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0, 10) # creates numpy range array 
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [15]:
np.zeros(5) # creates an array of zeros 0. indicates float

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2, 5)) # creates a 2D array of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((4, 4)) # creates a 2D array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.linspace(0, 10, 3) # creates an array of 3 evenly spaced numbers between 0 and 10
np.linspace(0, 10, 11) # 11 numbers between 0 and 10
np.linspace(0, 10, 21) 

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [26]:
np.eye(5) # creates an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(5) # creates an array of 5 random numbers between 0 and 1      
np.random.rand(5, 6) # creates a 2D array of random numbers

array([[0.97138715, 0.29540362, 0.59873196, 0.92163063, 0.5333998 ,
        0.80220637],
       [0.86905253, 0.05358041, 0.86603167, 0.80918263, 0.61296646,
        0.94987429],
       [0.97356252, 0.25667102, 0.84714528, 0.13233597, 0.52418061,
        0.46022988],
       [0.32758245, 0.51808157, 0.69558106, 0.1849613 , 0.54837321,
        0.51255823],
       [0.19230694, 0.94307399, 0.45797339, 0.07220993, 0.97672446,
        0.87745015]])

In [32]:
np.random.randn(10) # creates an array of 10 random numbers from a standard normal distribution

array([ 0.50784906,  1.60981337,  2.07870583, -2.10428107,  0.3114131 ,
        0.05122665,  1.13569228, -0.52380775, -1.54371699, -0.4875709 ])

In [34]:
np.random.randint(0, 101, 5) # creates an array of 5 random integers between 0 and 100
np.random.randint(0, 101, (4, 5)) # creates an array of 5 random integers between 0 and 100

array([[25, 68, 44, 14, 35],
       [65, 79, 78, 76, 59],
       [57, 84, 66, 72, 18],
       [52, 14, 23, 14, 89]])

In [38]:
np.random.seed(42) # sets the seed for reproducibility 
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [40]:
arr = np.arange(0, 25)

In [45]:
arr.reshape(5, 5) # reshapes the array into a 5x5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
ranarr = np.random.randint(0, 101, 10)

In [48]:
ranarr.max() # returns the maximum value in the array

99

In [49]:
ranarr.min() # returns the minimum value in the array

2

In [50]:
ranarr.argmax() # returns the index of the maximum value in the array

5

In [51]:
ranarr.argmin() # returns the index of the minimum value in the array

7

In [53]:
ranarr.dtype # returns the data type of the array

dtype('int32')

In [55]:
ranarr.shape # returns the shape of the array

(10,)

In [56]:
arr = arr.reshape(5, 5)

In [58]:
arr.shape

(5, 5)

In [63]:
arr.reshape(25, 1) # reshapes the array into a 25x1 matrix
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])