In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../../DATA/cancer_tumor_data_features.csv')

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler = StandardScaler()

In [6]:
scaled_X = scaler.fit_transform(df)

In [7]:
scaled_X

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [10]:
scaled_X -= scaled_X.mean(axis=0)

In [11]:
covariance_matrix = np.cov(scaled_X, rowvar=False)

In [13]:
pd.DataFrame(covariance_matrix, columns=df.columns, index=df.columns)

mean radius  mean texture  mean perimeter  mean area  \
mean radius                 1.001761      0.324352        0.999612   0.989095   
mean texture                0.324352      1.001761        0.330113   0.321651   
mean perimeter              0.999612      0.330113        1.001761   0.988244   
mean area                   0.989095      0.321651        0.988244   1.001761   
mean smoothness             0.170882     -0.023430        0.207643   0.177340   
mean compactness            0.507015      0.237119        0.557917   0.499379   
mean concavity              0.677955      0.302950        0.717396   0.687191   
mean concave points         0.823977      0.293981        0.852475   0.824718   
mean symmetry               0.148001      0.071527        0.183349   0.151559   
mean fractal dimension     -0.312179     -0.076572       -0.261937  -0.283608   
radius error                0.680286      0.276354        0.692983   0.733852   
texture error              -0.097489      0.387038       -0.086914  -0.066397   
perimeter error             0.675359      0.282169        0.694355   0.727908   
area error                  0.737159      0.260302        0.746294   0.801495   
smoothness error           -0.222992      0.006625       -0.203051  -0.167070   
compactness error           0.206363      0.192313        0.251185   0.212957   
concavity error             0.194546      0.143545        0.228484   0.208026   
concave points error        0.376831      0.164139        0.407934   0.372976   
symmetry error             -0.104505      0.009143       -0.081773  -0.072624   
fractal dimension error    -0.042716      0.054553       -0.005533  -0.019922   
worst radius                0.971246      0.353194        0.971183   0.964441   
worst texture               0.297531      0.913650        0.303572   0.287995   
worst perimeter             0.966836      0.358670        0.972095   0.960808   
worst area                  0.942739      0.344151        0.943207   0.960902   
worst smoothness            0.119827      0.077640        0.150814   0.123740   
worst compactness           0.414191      0.278319        0.456577   0.391098   
worst concavity             0.527839      0.301555        0.564872   0.513508   
worst concave points        0.745524      0.295836        0.772599   0.723288   
worst symmetry              0.164242      0.105193        0.189448   0.143823   
worst fractal dimension     0.007078      0.119415        0.051108   0.003744   

                         mean smoothness  mean compactness  mean concavity  \
mean radius                     0.170882          0.507015        0.677955   
mean texture                   -0.023430          0.237119        0.302950   
mean perimeter                  0.207643          0.557917        0.717396   
mean area                       0.177340          0.499379        0.687191   
mean smoothness                 1.001761          0.660284        0.522903   
mean compactness                0.660284          1.001761        0.884675   
mean concavity                  0.522903          0.884675        1.001761   
mean concave points             0.554670          0.832598        0.923013   
mean symmetry                   0.558757          0.603702        0.501548   
mean fractal dimension          0.585822          0.566364        0.337376   
radius error                    0.301998          0.498349        0.633037   
texture error                   0.068527          0.046286        0.076353   
perimeter error                 0.296613          0.549872        0.661553   
area error                      0.246987          0.456455        0.618514   
smoothness error                0.332961          0.135537        0.098737   
compactness error               0.319505          0.740022        0.671459   
concavity error                 0.248833          0.571521        0.692487   
concave points error            0.381346          0.643393        0.684463   
symmetry error                 

In [15]:
eigen_values, eigen_vectors = np.linalg.eigh(covariance_matrix)

In [19]:
print(pd.DataFrame(eigen_values, index=df.columns, columns=['eigen_values']))

                         eigen_values
mean radius                  0.000133
mean texture                 0.000750
mean perimeter               0.001592
mean area                    0.006913
mean smoothness              0.008192
mean compactness             0.015509
mean concavity               0.018087
mean concave points          0.024384
mean symmetry                0.027488
mean fractal dimension       0.030026
radius error                 0.031214
texture error                0.049565
perimeter error              0.052711
area error                   0.059504
smoothness error             0.080003
compactness error            0.094301
concavity error              0.157286
concave points error         0.241782
symmetry error               0.261621
fractal dimension error      0.294433
worst radius                 0.351311
worst texture                0.417629
worst perimeter              0.477456
worst area                   0.676409
worst smoothness             1.209482
worst compac

In [21]:
pd.DataFrame(eigen_vectors, index=df.columns, columns=df.columns).to_dict()

{'mean radius': {'mean radius': -0.7024140910482811,
  'mean texture': -0.00027366101787243413,
  'mean perimeter': 0.689896968467318,
  'mean area': 0.03294734818896938,
  'mean smoothness': 0.0048474576560832115,
  'mean compactness': -0.044674186257254694,
  'mean concavity': -0.025138666064925708,
  'mean concave points': 0.0010772653001909563,
  'mean symmetry': 0.0012803794083042774,
  'mean fractal dimension': 0.004755684796573161,
  'radius error': 0.008711093726172743,
  'texture error': 0.0010710391866500203,
  'perimeter error': -0.013729390592039946,
  'area error': -0.0011053260304242848,
  'smoothness error': 0.0016082108594233455,
  'compactness error': -0.0019156223503899,
  'concavity error': 0.008926526532995614,
  'concave points error': 0.002160197270682427,
  'symmetry error': -0.0003293897518038156,
  'fractal dimension error': -0.0017989568217677953,
  'worst radius': 0.13564305611639144,
  'worst texture': -0.00102053601376971,
  'worst perimeter': -0.0797438536

In [22]:
pd.DataFrame(eigen_vectors, index=df.columns, columns=df.columns)

mean radius  mean texture  mean perimeter  mean area  \
mean radius                -0.702414      0.211460        0.211194   0.131527   
mean texture               -0.000274     -0.010534       -0.000066   0.017357   
mean perimeter              0.689897      0.383826        0.084338   0.115415   
mean area                   0.032947     -0.422795       -0.272508  -0.466612   
mean smoothness             0.004847     -0.003435        0.001479  -0.069690   
mean compactness           -0.044674     -0.041017       -0.005463  -0.097749   
mean concavity             -0.025139     -0.010015        0.045539  -0.364808   
mean concave points         0.001077     -0.004207       -0.008883   0.454699   
mean symmetry               0.001280     -0.007570        0.001433   0.015165   
mean fractal dimension      0.004756      0.007301       -0.006312   0.101245   
radius error                0.008711      0.118442       -0.192224  -0.212983   
texture error               0.001071     -0.008776       -0.005623   0.010093   
perimeter error            -0.013729     -0.006100        0.263192  -0.041692   
area error                 -0.001105     -0.085926       -0.042068   0.313359   
smoothness error            0.001608      0.001776        0.009793   0.009052   
compactness error          -0.001916      0.003158       -0.015396  -0.046536   
concavity error             0.008927      0.016079        0.005821   0.084225   
concave points error        0.002160     -0.023938       -0.029009   0.011166   
symmetry error             -0.000329     -0.005223       -0.007637   0.019976   
fractal dimension error    -0.001799     -0.008342        0.019756   0.012037   
worst radius                0.135643     -0.635725        0.412640   0.178667   
worst texture              -0.001021      0.017235       -0.000390  -0.021411   
worst perimeter            -0.079744      0.022922       -0.728681   0.241031   
worst area                 -0.039742      0.444936        0.238960  -0.237162   
worst smoothness           -0.004583      0.007385       -0.001535   0.040854   
worst compactness           0.012842      0.000004        0.048692   0.070505   
worst concavity            -0.000402     -0.012676       -0.017641   0.142906   
worst concave points        0.002288      0.035240        0.022476  -0.230901   
worst symmetry             -0.000395      0.013404        0.004920  -0.022790   
worst fractal dimension    -0.001894      0.011478       -0.023562  -0.059986   

                         mean smoothness  mean compactness  mean concavity  \
mean radius                     0.129476         -0.019226       -0.182579   
mean texture                    0.024557          0.084746        0.098787   
mean perimeter                  0.125256          0.027015       -0.116649   
mean area                      -0.362727         -0.210041        0.069848   
mean smoothness                 0.037004          0.028955        0.068697   
mean compactness               -0.262808          0.396623       -0.104136   
mean concavity                  0.548876         -0.096977        0.044741   
mean concave points            -0.387643         -0.186452        0.084028   
mean symmetry                   0.016044         -0.024584        0.019339   
mean fractal dimension          0.097405         -0.207222       -0.133261   
radius error                   -0.049977         -0.174930       -0.558702   
texture error                   0.011237          0.056986        0.024267   
perimeter error                -0.103653          0.072928        0.516750   
area error                      0.155305          0.131850       -0.022461   
smoothness error                0.007718          0.031211        0.015631   
compactness error               0.049728          0.173165       -0.121778   
concavity error                -0.091455          0.015940        0.188205   
concave points error            0.017942         -0.129547       -0.109669   
symmetry error                 

In [27]:
num_components = 4

In [28]:
sorted_key = np.argsort(eigen_values)[::-1][:num_components]

In [30]:
pd.DataFrame(sorted_key, index=range(1, num_components+1), columns=['sorted_key'])

sorted_key
1          29
2          28
3          27
4          26

In [31]:
eigen_values, eigen_vectors = eigen_values[sorted_key], eigen_vectors[:, sorted_key]

In [33]:
pd.DataFrame(eigen_values, index=range(1, num_components+1), columns=['eigen_values'])

eigen_values
1     13.304991
2      5.701375
3      2.822910
4      1.984128

In [34]:
pd.DataFrame(eigen_vectors, index=df.columns, columns=range(1, num_components+1))

1         2         3         4
mean radius             -0.218902  0.233857  0.008531 -0.041409
mean texture            -0.103725  0.059706 -0.064550  0.603050
mean perimeter          -0.227537  0.215181  0.009314 -0.041983
mean area               -0.220995  0.231077 -0.028700 -0.053434
mean smoothness         -0.142590 -0.186113  0.104292 -0.159383
mean compactness        -0.239285 -0.151892  0.074092 -0.031795
mean concavity          -0.258400 -0.060165 -0.002734 -0.019123
mean concave points     -0.260854  0.034768  0.025564 -0.065336
mean symmetry           -0.138167 -0.190349  0.040240 -0.067125
mean fractal dimension  -0.064363 -0.366575  0.022574 -0.048587
radius error            -0.205979  0.105552 -0.268481 -0.097941
texture error           -0.017428 -0.089980 -0.374634  0.359856
perimeter error         -0.211326  0.089457 -0.266645 -0.088992
area error              -0.202870  0.152293 -0.216007 -0.108205
smoothness error        -0.014531 -0.204430 -0.308839 -0.044664
compactness error       -0.170393 -0.232716 -0.154780  0.027469
concavity error         -0.153590 -0.197207 -0.176464 -0.001317
concave points error    -0.183417 -0.130322 -0.224658 -0.074067
symmetry error          -0.042498 -0.183848 -0.288584 -0.044073
fractal dimension error -0.102568 -0.280092 -0.211504 -0.015305
worst radius            -0.227997  0.219866  0.047507 -0.015417
worst texture           -0.104469  0.045467  0.042298  0.632808
worst perimeter         -0.236640  0.199878  0.048547 -0.013803
worst area              -0.224871  0.219352  0.011902 -0.025895
worst smoothness        -0.127953 -0.172304  0.259798 -0.017652
worst compactness       -0.210096 -0.143593  0.236076  0.091328
worst concavity         -0.228768 -0.097964  0.173057  0.073951
worst concave points    -0.250886  0.008257  0.170344 -0.006007
worst symmetry          -0.122905 -0.141883  0.271313  0.036251
worst fractal dimension -0.131784 -0.275339  0.232791  0.077053

In [36]:
principal_components = np.dot(scaled_X, eigen_vectors)

In [39]:
principal_components

array([[ -9.19283683,  -1.94858307,   1.12316616,  -3.6337309 ],
       [ -2.3878018 ,   3.76817174,   0.52929269,  -1.11826386],
       [ -5.73389628,   1.0751738 ,   0.55174759,  -0.91208267],
       ...,
       [ -1.25617928,   1.90229671,  -0.56273053,   2.08922702],
       [-10.37479406,  -1.67201011,   1.87702933,   2.35603113],
       [  5.4752433 ,   0.67063679,  -1.49044308,   2.29915714]])

In [40]:
principal_component = np.dot(scaled_X, eigen_vectors)

In [41]:
principal_component

array([[ -9.19283683,  -1.94858307,   1.12316616,  -3.6337309 ],
       [ -2.3878018 ,   3.76817174,   0.52929269,  -1.11826386],
       [ -5.73389628,   1.0751738 ,   0.55174759,  -0.91208267],
       ...,
       [ -1.25617928,   1.90229671,  -0.56273053,   2.08922702],
       [-10.37479406,  -1.67201011,   1.87702933,   2.35603113],
       [  5.4752433 ,   0.67063679,  -1.49044308,   2.29915714]])

In [55]:
%matplotlib notebook

In [57]:
plt.figure(figsize=(8,6))
plt.scatter(principal_components[:,0],principal_components[:,1], c='r', edgecolors='k', alpha=0.6, s=50)
plt.grid()
plt.title('First two principal components')
plt.xlabel('First principal component')
plt.ylabel('Second Principal Component')

<IPython.core.display.Javascript object>

Text(0, 0.5, 'Second Principal Component')

In [58]:
from sklearn.datasets import load_breast_cancer

In [59]:
cancer_dictionary = load_breast_cancer()

In [60]:
cancer_dictionary.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [61]:
cancer_dictionary['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [62]:
plt.figure(figsize=(8,6))
plt.scatter(principal_components[:,0],principal_components[:,1],c=cancer_dictionary['target'])
plt.xlabel('First principal component')
plt.ylabel('Second Principal Component')

<IPython.core.display.Javascript object>

Text(0, 0.5, 'Second Principal Component')