In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df = pd.read_csv("../../DATA/Advertising.csv")

In [30]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [31]:
X = df.drop('sales', axis=1)

In [32]:
y = df['sales']

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=101)

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
scaler = StandardScaler()

In [37]:
scaler.fit(X_train, y_train)

StandardScaler()

In [40]:
scaled_X_train = scaler.fit_transform(X_train)

In [41]:
scaled_X_test = scaler.fit_transform(X_test)

In [42]:
from sklearn.linear_model import Ridge

In [43]:
model_ridge = Ridge(alpha=100)

In [44]:
model_ridge.fit(X_train, y_train)

Ridge(alpha=100)

In [45]:
model_ridge.predict(X_test)

array([15.72580396, 19.60445215, 11.45409585, 16.99459935,  9.16785549,
        7.01628804, 20.28398161, 17.29606392,  9.78724242, 19.21625134,
       12.39076855, 13.89357894, 13.73635623, 21.2744788 , 18.42292234,
        9.97886125, 15.56408955,  7.70065832,  7.56236405, 20.39349034,
        7.79238957, 18.23201812, 24.67049481, 22.81228464,  7.98482389,
       12.66638658, 21.46198286,  8.06184873, 12.43029793, 12.49755594,
       10.77478415, 19.23976286, 10.07967196,  6.71568227, 17.30922969,
        7.78241277,  9.26109689,  8.28759023, 10.57400415, 10.64672333,
       13.01325248,  9.78576552, 10.22172507,  8.04977137, 11.56360884,
       10.08381587,  8.99052558, 16.26179595, 13.2519985 , 20.80158884,
       12.48856158, 13.97566036, 17.57043162, 11.14753959, 12.57530225,
        5.51307186, 23.2769006 , 12.60839371, 18.77175383, 15.18852567])

In [46]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [48]:
MAE = mean_absolute_error(y_test, model_ridge.predict(X_test))
MSE = mean_squared_error(y_test, model_ridge.predict(X_test))
RMSE = np.sqrt(MSE)

In [49]:
print(f"MAE: {MAE}, MSE: {MSE}, RMSE: {RMSE}")

MAE: 1.2137706010738254, MSE: 2.29986994221135, RMSE: 1.5165322094210034


In [50]:
ridge_model = Ridge(alpha=1)

In [51]:
ridge_model.fit(scaled_X_train, y_train)

Ridge(alpha=1)

In [52]:
ridge_model.predict(X_test)

C:\Users\Zygim\anaconda3\envs\Analytic\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but Ridge was fitted without feature names
  warnings.warn(


array([ 429.3757222 , 1043.25908053,  484.37716065,  556.25998353,
        199.63681929,  130.83639759, 1075.80132542,  879.90258139,
        544.21906329,  930.12562246,  267.06341339,  713.63827854,
        855.36986421,  893.87468372,  836.04372962,  252.34297152,
       1007.11606418,  376.05542407,  233.18119479,  970.50839115,
        142.82365924,  763.9769459 , 1184.14354704, 1108.82257239,
        297.87389698,  770.08887111, 1188.29835128,  270.24583831,
        661.08720622,  204.80443008,  199.83317276,  928.3506795 ,
        530.01649519,  107.44968268,  768.00335883,  382.00008551,
        372.86409129,  380.05459955,  159.4687483 ,  607.0942939 ,
        368.6228278 ,  541.8236399 ,  414.78993095,  144.31340018,
        373.36372218,  329.41010271,  116.59947281,  907.45419836,
        720.23490248,  876.10081312,  288.71540514,  811.16543121,
       1089.93208768,  492.95736441,  768.68045834,   61.49860025,
       1132.65007436,  274.85226263, 1062.45023888,  730.96065

In [54]:
y_pred = ridge_model.predict(scaled_X_test)

In [55]:
MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)
RMSE = np.sqrt(MSE)

In [56]:
print(f"MAE: {MAE}, MSE: {MSE}, RMSE: {RMSE}")

MAE: 1.4000323278889415, MSE: 3.3393710384440864, RMSE: 1.8273946039222306


In [57]:
X = df.drop('sales', axis=1)

In [58]:
y = df['sales']

In [59]:
X_train, X_OTHER, y_train, y_OTHER = train_test_split(X, y, test_size=0.3, random_state=101)

In [60]:
X_eval, X_test, y_eval, y_test = train_test_split(X_OTHER, y_OTHER, test_size=0.5, random_state=101)

In [61]:
from sklearn.preprocessing import StandardScaler

In [62]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_eval = scaler.transform(X_eval)
X_test = scaler.transform(X_test)

In [63]:
from sklearn.linear_model import Ridge

In [64]:
model = Ridge(alpha=100)

In [65]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [66]:
y_eval_pred = model.predict(X_eval)

In [67]:
from sklearn.metrics import mean_squared_error

In [68]:
mean_squared_error(y_eval,y_eval_pred)

7.320101458823871

In [69]:
model = Ridge(alpha=1)

In [70]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [71]:
y_eval_pred = model.predict(X_eval)

In [72]:
mean_squared_error(y_eval,y_eval_pred)

2.3837830750569853

In [73]:
y_final_test_pred = model.predict(X_test)

In [74]:
mean_squared_error(y_test,y_final_test_pred)

2.254260083800517

In [75]:
X = df.drop('sales',axis=1)
y = df['sales']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [76]:
model = Ridge(alpha=100)

In [77]:
from sklearn.model_selection import cross_val_score

In [78]:
scores = cross_val_score(
    model, X_train, y_train,
    scoring='neg_mean_squared_error',
    cv=5,
    n_jobs=-1,
    verbose=2,
)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 24 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   5 | elapsed:    1.7s remaining:    1.1s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    1.7s finished


In [79]:
scores

array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
        -8.38562723])

In [80]:
abs(scores.mean())

8.215396464543609

In [81]:
model = Ridge(alpha=1)

In [82]:
scores = cross_val_score(
    model, X_train, y_train,
    scoring='neg_mean_squared_error',
    cv=5,
    n_jobs=-1,
    verbose=2,
)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 24 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   5 | elapsed:    1.0s remaining:    0.6s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    1.0s finished


In [84]:
scores

array([-3.15513238, -1.58086982, -5.40455562, -2.21654481, -4.36709384])

In [85]:
abs(scores.mean())

3.344839296530696

In [86]:
model.fit(X_train, y_train)

Ridge(alpha=1)

In [87]:
y_final_test_pred = model.predict(X_test)

In [88]:
mean_squared_error(y_test,y_final_test_pred)

2.319021579428751

In [89]:
X = df.drop('sales',axis=1)
y = df['sales']


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)


from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [90]:
model = Ridge(alpha=100)

In [91]:
from sklearn.model_selection import cross_validate

In [93]:
scores = cross_validate(model,X_train,y_train,
                        scoring=['neg_mean_absolute_error','neg_mean_squared_error','max_error'],cv=5)

In [94]:
scores

{'fit_time': array([0.00100064, 0.00100613, 0.        , 0.00050521, 0.00100923]),
 'score_time': array([0.00116634, 0.00050521, 0.0010066 , 0.00100636, 0.        ]),
 'test_neg_mean_absolute_error': array([-2.31243044, -1.74653361, -2.56211701, -2.01873159, -2.27951906]),
 'test_neg_mean_squared_error': array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
         -8.38562723]),
 'test_max_error': array([ -6.44988486,  -5.58926073, -10.33914027,  -6.61950405,
         -7.75578515])}

In [95]:
pd.DataFrame(scores)

fit_time  score_time  test_neg_mean_absolute_error  \
0  0.001001    0.001166                     -2.312430   
1  0.001006    0.000505                     -1.746534   
2  0.000000    0.001007                     -2.562117   
3  0.000505    0.001006                     -2.018732   
4  0.001009    0.000000                     -2.279519   

   test_neg_mean_squared_error  test_max_error  
0                    -9.325530       -6.449885  
1                    -4.944962       -5.589261  
2                   -11.396652      -10.339140  
3                    -7.024211       -6.619504  
4                    -8.385627       -7.755785

In [96]:
pd.DataFrame(scores).mean()

fit_time                        0.000704
score_time                      0.000737
test_neg_mean_absolute_error   -2.183866
test_neg_mean_squared_error    -8.215396
test_max_error                 -7.350715
dtype: float64

In [97]:
scores = cross_validate(model,X_train,y_train,
                        scoring=['neg_mean_absolute_error','neg_mean_squared_error','max_error'],cv=5)

In [98]:
pd.DataFrame(scores).mean()

fit_time                        0.000903
score_time                      0.000870
test_neg_mean_absolute_error   -2.183866
test_neg_mean_squared_error    -8.215396
test_max_error                 -7.350715
dtype: float64

In [99]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [100]:
y_final_test_pred = model.predict(X_test)

In [101]:
mean_squared_error(y_test,y_final_test_pred)

7.34177578903413